//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_
    {
        public int Id_Produto { get; set; }
        public string Descricao { get; set; }
        public string Quantidade { get; set; }
        public int Preco_Venda { get; set; }
    }
}
